### ISSUE TITLE
Dead programs policy

### ISSUE THREAD

**Issue by 0xn3va** [nikitastupin/orgs-data#13]
Hi there!

When I looked through the immunefi list I found that there are a lot of dead programs. We have already discussed dead programs earlier in the PR and came to the conclusion that it makes sense to leave links somewhere since programs can migrate somewhere else. However, this creates a slight inconvenience if you have a need to work with actual programs only. What do you think about creating a separate list with dead links like `immunefi.inactive.tsv` or `immunefi.old.tsv`? Such a list can be used as a kind of quarantine in which links remain until they appear on other platforms.

**Comment by nikitastupin** [comment]
Hey @0xn3va,

I see, this'll add some additional work (to sort things out to different files) though.

However, if you see benefits I'm open to try it. Would you be willing to make a PR separating the active and inactive programs?

With regards to naming I'd go with .inactive.

**Comment by 0xn3va** [comment]
Hey @nikitastupin,

Sure, I will do in a while

**Comment by nikitastupin** [comment]
I believe this is not finished yet so reopening

**Comment by nikitastupin** [comment]
https://github.com/nikitastupin/orgs-data/commit/81a81174e93b7247352e8f2914189bd7639b0d14#diff-6a61b824c799c6ef796cd61f957d78017211c0d58defbe22ffd6a842378521d4R382 - cases like this one happen from time to time (programs disappear but then appear again) so I'd prefer to keep all programs in one file without dividing to active and inactive to keep it simple. Thanks for the idea though!
